# Generated by Django 3.1.5 on 2021-01-27 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contraindication',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('shelf_life', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Drug_Description',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Indication',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=40, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_name', to='myApp.country')),
            ],
        ),
        migrations.CreateModel(
            name='Drug_Store',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=40, null=True)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialization_id', to='myApp.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='Drug_Drug_Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_id', to='myApp.drug')),
                ('drug_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_store_id', to='myApp.drug_store')),
            ],
        ),
        migrations.CreateModel(
            name='Drug_Description_Indication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_description1', to='myApp.drug_description')),
                ('indication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indication_name', to='myApp.indication')),
            ],
        ),
        migrations.CreateModel(
            name='Drug_Description_Contraindication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_description2', to='myApp.drug_description')),
                ('indication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contraindication_name', to='myApp.contraindication')),
            ],
        ),
        migrations.AddField(
            model_name='drug_description',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_description_group', to='myApp.group'),
        ),
        migrations.AddField(
            model_name='drug',
            name='drug_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_description3', to='myApp.drug_description'),
        ),
        migrations.AddField(
            model_name='drug',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_id', to='myApp.manufacturer'),
        ),
        migrations.AddField(
            model_name='drug',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_id', to='myApp.type'),
        ),
    ]
